In [1]:
#creating numpy/n-d arrays
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5 = np.identity(5)

In [12]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr7 = np.arange(5,15)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
#if i have to generate array from 5 to 15 level 1 element in b/w
arr8 = np.arange(5,15,2)
arr8

array([ 5,  7,  9, 11, 13])

In [17]:
#linspace is used to create array of size n from x to y which equal space in between 
#every element 
#arr = np.linspace(x,y,n)
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
arr10 = arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# properties and Attributes

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
arr1.shape

(5,)

In [21]:
arr2.shape

(2, 3)

In [27]:
#array is a function
arr11 = np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [23]:
arr11.shape

(2, 2, 2)

In [28]:
#ndim is a attribute
arr11.ndim

3

In [25]:
arr2.ndim

2

In [26]:
arr1.ndim

1

In [29]:
arr1.size

5

In [30]:
arr11.size

8

In [31]:
arr11.itemsize

8

In [33]:
#it gives 8 becuase it contains float
arr10.itemsize

8

In [34]:
arr10.dtype

dtype('float64')

In [35]:
arr11.dtype

dtype('int64')

In [38]:
#it is used to convert type of array
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [6., 7.]]])

In [39]:
lista = range(100)
arr12 = np.arange(100)

In [40]:
#sys stands for system
import sys

In [41]:
# as 87 lie in b/t 0 to 100 so it a element of arr which is divide by len of list
print(sys.getsizeof(87)*len(lista))

2800


In [42]:
print(arr12.itemsize*arr12.size)

800


In [43]:
#it is used to mearsure speed
import time

In [46]:
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()

#zip is a function joh cheezo ko nikal kar zip karta in one
c = [(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

2.526440382003784


In [47]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()

c = a+b

print(time.time()-start)

1.07515549659729


## Indexing, Slicing and iteration

In [49]:
# reshape is used to change the shape of array
arr13 = np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
arr1

array([1, 2, 3, 4, 5])

In [52]:
arr1[2:4]

array([3, 4])

In [54]:
arr1[-1]

np.int64(5)

In [55]:
arr13[2]

array([ 8,  9, 10, 11])

In [59]:
arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [61]:
arr13[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [62]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [63]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [67]:
# nditer is a function iter for iteration
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
