In [1]:
import numpy as np

In [2]:
np.random.random()

0.3291855553420967

In [5]:
# seed gives same random value again and again
np.random.seed(1)
np.random.random()

0.417022004702574

In [7]:
#to get random value in a given range
np.random.uniform(3,10)

3.000800623721414

In [8]:
np.random.uniform(1,100,10)

array([30.93092469, 15.52883319, 10.14152088, 19.43976093, 35.21051198,
       40.27997995, 54.34285667, 42.50025693, 68.83673054, 21.24077272])

In [10]:
np.random.uniform(1,10,10).reshape(5,2)

array([[7.23090354, 8.88750237],
       [9.05145997, 1.7653979 ],
       [1.35149305, 2.52847378],
       [8.90328253, 1.8851215 ],
       [4.78996863, 9.62100577]])

In [11]:
# to get random integer value in range
np.random.randint(1,10)

4

In [12]:
np.random.randint(1,100,10)

array([69, 25, 44, 77, 27, 53, 81, 42, 83, 16], dtype=int32)

In [13]:
np.random.randint(1,100,10).reshape(2,5)

array([[65, 69, 26, 99, 88],
       [ 8, 27, 26, 23, 10]], dtype=int32)

In [15]:
a=np.random.randint(1,10,6)
a

array([4, 8, 8, 5, 6, 4], dtype=int32)

In [16]:
np.max(a)

np.int32(8)

In [17]:
np.min(a)

np.int32(4)

In [20]:
a[np.argmax(a)]

np.int32(8)

In [21]:
a[np.argmin(a)]

np.int32(4)

In [23]:
np.argmax(a)

np.int64(1)

In [24]:
np.argmin(a)

np.int64(0)

In [25]:
a=np.random.randint(1,10,6)

In [26]:
a

array([7, 9, 1, 3, 8, 8], dtype=int32)

In [27]:
a[a%2==1] = -1
a

array([-1, -1, -1, -1,  8,  8], dtype=int32)

In [33]:
a=np.random.randint(1,50,6)
a

array([44, 21, 31, 37, 40,  8], dtype=int32)

In [34]:
np.where(a%2==1,-1,a)

array([44, -1, -1, -1, 40,  8], dtype=int32)

In [35]:
a

array([44, 21, 31, 37, 40,  8], dtype=int32)

In [37]:
# where modifies the value according to the condition
out = np.where(a%2==1,-1,a)
out

array([44, -1, -1, -1, 40,  8], dtype=int32)

In [39]:
a=np.random.randint(1,50,10)
a

array([11, 24, 18,  8, 25, 11, 29, 21, 33, 13], dtype=int32)

In [40]:
a = np.sort(a)
a

array([ 8, 11, 11, 13, 18, 21, 24, 25, 29, 33], dtype=int32)

In [41]:
np.percentile(a,25)

np.float64(11.5)

In [43]:
np.percentile(a,50)

np.float64(19.5)

In [44]:
np.percentile(a,100)

np.float64(33.0)